development:
  bucket: 'teneventsdevelopment'
  access_key_id: 'AKIAIGMYXWNKAALT72YQ'
  secret_access_key: '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'

test:
  bucket: 'teneventstest'
  access_key_id: 'AKIAIGMYXWNKAALT72YQ'
  secret_access_key: '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'

production:
  bucket: 'tenevents'
  access_key_id: 'AKIAIGMYXWNKAALT72YQ'
  secret_access_key: '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'
